boot.o: boot.S includes/multiboot.h includes/x86_desc.h includes/types.h
init_helpers.o: src/init_helpers.S
x86_desc.o: src/x86_desc.S includes/x86_desc.h includes/types.h
handle.o: src/handle.c includes/handle.h includes/lib.h includes/types.h \
  includes/drivers/i8259.h includes/types.h includes/drivers/rtc.h \
  includes/lib.h includes/drivers/i8259.h
idt.o: src/idt.c includes/idt.h includes/x86_desc.h includes/types.h \
  includes/handle.h includes/drivers/intr_link.h
kernel.o: src/kernel.c includes/multiboot.h includes/types.h \
  includes/x86_desc.h includes/lib.h includes/drivers/i8259.h \
  includes/types.h includes/debug.h includes/tests.h \
  includes/init_helpers.h includes/idt.h includes/x86_desc.h \
  includes/handle.h includes/drivers/intr_link.h \
  includes/drivers/keyboard.h includes/lib.h includes/drivers/i8259.h \
  includes/drivers/rtc.h
lib.o: src/lib.c includes/lib.h includes/types.h
tests.o: src/tests.c includes/tests.h includes/x86_desc.h \
  includes/types.h includes/lib.h includes/drivers/rtc.h includes/lib.h \
  includes/drivers/i8259.h includes/types.h includes/handle.h \
  includes/drivers/i8259.h
i8259.o: src/devices/i8259.c includes/drivers/i8259.h includes/types.h \
  includes/lib.h includes/types.h
keyboard.o: src/devices/keyboard.c includes/drivers/keyboard.h \
  includes/lib.h includes/types.h includes/drivers/i8259.h \
  includes/types.h
rtc.o: src/devices/rtc.c includes/drivers/rtc.h includes/lib.h \
  includes/types.h includes/drivers/i8259.h includes/types.h
intr_link.o: src/devices/intr_link.S
