boot.o: boot.S includes/multiboot.h includes/x86_desc.h includes/types.h
init_helpers.o: src/init_helpers.S
intr_link.o: src/intr_link.S
x86_desc.o: src/x86_desc.S includes/x86_desc.h includes/types.h
handle.o: src/handle.c includes/handle.h includes/lib.h includes/types.h \
  includes/i8259.h includes/rtc.h includes/lib.h includes/i8259.h
i8259.o: src/i8259.c includes/i8259.h includes/types.h includes/lib.h
idt.o: src/idt.c includes/idt.h includes/x86_desc.h includes/types.h \
  includes/handle.h includes/intr_link.h includes/keyboard.h \
  includes/lib.h includes/i8259.h includes/terminal.h includes/vfs.h \
  includes/rtc.h
kernel.o: src/kernel.c includes/multiboot.h includes/types.h \
  includes/x86_desc.h includes/lib.h includes/i8259.h includes/debug.h \
  includes/tests.h includes/init_helpers.h includes/idt.h \
  includes/x86_desc.h includes/handle.h includes/intr_link.h \
  includes/keyboard.h includes/lib.h includes/i8259.h includes/terminal.h \
  includes/vfs.h includes/rtc.h includes/keyboard.h includes/rtc.h \
  includes/mp3fs.h includes/multiboot.h includes/vfs.h
keyboard.o: src/keyboard.c includes/keyboard.h includes/lib.h \
  includes/types.h includes/i8259.h includes/terminal.h includes/vfs.h
lib.o: src/lib.c includes/lib.h includes/types.h
mp3fs.o: src/mp3fs.c includes/mp3fs.h includes/types.h \
  includes/multiboot.h includes/vfs.h includes/lib.h
rtc.o: src/rtc.c includes/rtc.h includes/lib.h includes/types.h \
  includes/i8259.h
terminal.o: src/terminal.c includes/terminal.h includes/lib.h \
  includes/types.h includes/vfs.h
tests.o: src/tests.c includes/tests.h includes/x86_desc.h \
  includes/types.h includes/lib.h includes/rtc.h includes/lib.h \
  includes/i8259.h includes/handle.h includes/i8259.h includes/mp3fs.h \
  includes/multiboot.h includes/vfs.h includes/vfs.h includes/terminal.h
vfs.o: src/vfs.c includes/vfs.h includes/types.h includes/lib.h \
  includes/mp3fs.h includes/multiboot.h includes/vfs.h \
  includes/terminal.h includes/lib.h
